### ISSUE TITLE
OptimizeRelativePositionWithKnownRotation

### ISSUE THREAD

**Issue by Heusini** [urbste/pyTheiaSfM#10]
Hi,
is there a reason why this function is not wrapped?

https://github.com/urbste/pyTheiaSfM/blob/2353f089408c06496066beccd75ae227a044be1b/src/pytheia/sfm/sfm.cc#L1485

**Comment by urbste** [comment]
No reason probably got forgotten ;) . You want to create a PR?

**Comment by urbste** [comment]
Closing as done in #11
