### ISSUE TITLE
Error in FilterViewPairsFromOrientation and FilterViewPairsFromRelativeTranslation

### ISSUE THREAD

**Issue by Heusini** [urbste/pyTheiaSfM#12]
I think there is an error in the Wrapper function for filtering view pairs.
In the wrapper function the ViewGraph is created and than the original function is called. So there is always an empty ViewGraph

https://github.com/urbste/pyTheiaSfM/blob/2353f089408c06496066beccd75ae227a044be1b/src/theia/sfm/sfm_wrapper.cc#L48-L55

But in the original theia function **a not empty** ViewGraph is needed as we can see here in line 66
https://github.com/urbste/pyTheiaSfM/blob/2353f089408c06496066beccd75ae227a044be1b/src/theia/sfm/filter_view_pairs_from_orientation.cc#L51-L66

The same thing is true for FilterViewPairsFromRelativeTranslation.

**Comment by urbste** [comment]
yep I am on it.

**Comment by Heusini** [comment]
Hi, I think your example is not using the FilterViewPairsFromOrientation. 
Nonetheless I tested it with my code and it seems to work.
