### ISSUE TITLE
Question regarding BundleAdjustment bindings usage

### ISSUE THREAD

**Issue by GrapixLeGrand** [urbste/pyTheiaSfM#13]
Hello,

I would have a question regarding the BA example in the README.md bellow:

```
import pytheia as pt
recon = pt.sfm.Reconstruction()
# add some views and points
veiw_id = recon.AddView() 
...
track_id = recon.AddTrack()
...
covariance = np.eye(2) * 0.5**2
point = [200,200]
recon.AddObservation(track_id, view_id, pt.sfm.Feature(point, covariance))

# robust BA
opts = pt.sfm.BundleAdjustmentOptions()
opts.robust_loss_width = 1.345
opts.loss_function_type = pt.sfm.LossFunctionType.HUBER

res = BundleAdjustReconstruction(opts, recon)
res = BundleAdjustPartialReconstruction(opts, {view_ids}, {track_ids}, recon)
res = BundleAdjustPartialViewConstant(opts, {var_view_ids}, {const_view_ids}, recon)

# optimize absolute pose on normalized 2D 3D correspondences
res = pt.sfm.OptimizeAbsolutePoseOnNormFeatures(
  [pt.sfm.FeatureCorrespondence2D3D], R_init, p_init, opts)

# bundle camera adjust pose only
res = BundleAdjustView(recon, opts, view_id)
res = BundleAdjustViewWithCov(recon, view_id)
res = BundleAdjustViewsWithCov(recon, opts, [view_id1,view_id2])

# optimize structure only
res = BundleAdjustTrack(recon, opts, trackid)
res = BundleAdjustTrackWithCov(recon, opts, [view_id1,view_id2])
res = BundleAdjustTracksWithCov(recon, opts, [view_id1,trackid])

# two view optimization
res = BundleAdjustTwoViewsAngular(recon, [pt.sfm.FeatureCorrespondence], pt.sfm.TwoViewInfo()) 
```

I'm trying to compute the final 3D points given that I have at disposal image views each with the following data:
- key points
- global translation
- global rotation

I also have view pairs that overlapped where I have the following data:
- relative translation
- relative rotation
- matchings (ids of keypoints that matched in both views)

Then given all of the above, I would have the following questions if possible:

1. Is that correct that I can use the `BundleAdjustReconstruction` to reconstruct the final 3D points? The doc in c++ says "Bundle adjust all views and tracks in the reconstruction.".
2.  I don't understand what exactly a Track is (neither from the c++ code doc). Is that supposed to be the conceptual idea of capturing images with the same device along a path in the reconstruction scene (like a video) which then forms a track? If that's correct and that I don't have such track but all my images should make a single set, should I only create a single Track where all images are related to it? 
3. From the documentation (in c++) of Reconstruction (reconstruction.h) concerning the function `AddObservation` says that the function will return false when an observation was already added for the track. What exactly an observation is? Should it be a 2D keypoint point? Sorry for my confusion, I'm a bit new to SFM.

Thanks a lot for your time and thanks for maintaining these bindings!
Best,
Quentin

**Comment by urbste** [comment]
Hi,

To your general questions.:

A track is just a different word for a 3D point. It is called track as usually you can "track" or "match" this point in different images either in a video or in still images. 

An observation is a 2D - 3D correspondence. So each track (3d point) has multiple 2D observations.

A view is just one single image in your reconstruction, that hold 2D-3D matches for that view and also the camera extrinsics and intrinsics.

Usually you would use the TrackBuilder() to create tracks from two view matches. Otherwise, if you observe a known target (e.g. Aruco markers) you can create the tracks yourself, as you already know their coordinates and the 2D correspondences are simple to establish. 
In the first case, you would also need to triangulate the position of a track first, before you can run BundleAdjust on it.

Have  a look a the ReconstructionEstimator class. 

1. You will need to triangulate it first before you can run bundle adjustment. Have a look at: TriangulateDLT

e.g. what you could do (did not test it so it might have some errors ;)):
``` Python
recon = pt.sfm.Reconstruction()
# create two views
v_id1, v_id2 = recon.AddView("v1",0,0),  recon.AddView("v2",0,1)
v1, v2 = recon.MutableView(v_id1), recon.MutableView(v_id2)

# if you know extrinsics set them here (see that we need MutableCamera() not Camera())
c1, c2 = v1.MutableCamera(), v2.MutableCamera()
c1.SetPosition(np.array([0,0,0]))
c2.SetPosition(np.aray([1,0,0]))
c1.SetOrientationFromRotationMatrix(np.eye(3))
c2.SetOrientationFromRotationMatrix(np.eye(3))

# now add a track
t_id = recon.AddTrack()

# now say you have an obervation in cam 1 and cam 2
obs1 = np.array([100,100])
obs2 = np.array([110,100])
p = pt.sfm.TriangulateDLT(c1.GetProjectionMatrix(), c2.GetProjectionMatrix(), obs1,obs2)

# now set the coordinate of that point
recon.MutableTrack(t_id).SetPoint(p)
# Add the observations to the reconstruction
recon.AddObservation(t_id, v_id1, pt.sfm.Feature(obs1))
recon.AddObservation(t_id, v_id2, pt.sfm.Feature(obs2))

# and run bundle adjustment
sum = pt.sfm.BundleAdjustTrack(recon, options, t_id)

```

3. Yes observation is a 2D observation, e.g. keypoint.

**Comment by GrapixLeGrand** [comment]
Okay! thanks a lot for the quick reply it is much clearer now. I will try it out. 

Best regards,
Quentin

**Comment by GrapixLeGrand** [comment]
Hello again,

I was trying to make a similar code as you showed and went through the following question. Given that I have $N$ views that observed the same 3D point $p$ (our track. 
1. I should, instead of triangulate only the views 2 by 2, triangulate a track estimate initially given these $N$ views right? There is a function (in the same file as `TriangulateDLT` that is called (and binded) `TriangulateNView`. Should I use that? 
2. Then, Given the points that matched during my feature-matching step (my 2D correspondence matching step), I should add all these observations at the same time to triangulate the Track right? 
3. Point 2 means that I could use the function AddTrack that takes a vector of (viewIds, Feature) where each view would deliver its own observation of the similar point or track.
4. I didn't get how to access the triangulated 3D points at the end or by which structure. Is it by accessing each track object? Then also, I want to bundle adjust the whole scene, meaning that I understand I would need to perform the following:
- initialize all tracks with estimate (given $N$ views looking at the point.
- triangulate the tracks (I guess there is a way to make it constraint to all the tracks at the same time.
- retrieve the track's positions

Thanks a lot for your time in advance. Sorry for my confusion, I'm a bit new to SFM :)

Best,
Quentin
