### ISSUE TITLE
Error in sfm_pipeline example setting the camera intrinsics

### ISSUE THREAD

**Issue by Heusini** [urbste/pyTheiaSfM#16]
I think there is an error in the pytest/sfm_pipeline.py example code. 
This line does not correctly change the focal length of the cameras.
https://github.com/urbste/pyTheiaSfM/blob/25a8cbf0f9cc8a4ba0b359948c0d294225aad18d/pytest/sfm_pipeline.py#L223

The focal length is later used here:
https://github.com/urbste/pyTheiaSfM/blob/25a8cbf0f9cc8a4ba0b359948c0d294225aad18d/pytest/sfm_pipeline.py#L134-L136
and than called in theia here:

https://github.com/urbste/pyTheiaSfM/blob/25a8cbf0f9cc8a4ba0b359948c0d294225aad18d/src/theia/sfm/estimate_twoview_info.cc#L154-L165

I could set the focal length like this:
```python
v.Camera().SetFromCameraIntrinsicsPriors(prior)
```
But setting the intrinsics like that the problem is still that the image_width and height is not set which is also used in the theia code and thus both values are zero.

Before I continue on this journey I wanted to quickly check if I got this right. The focal length as well as all those other parameters should be set for the camera?

**Comment by urbste** [comment]
Yes they should all be set. You might be right that it does not work correctly. I am current on vacation without access to a Laptop. I can have a look next week.

Did you try calling pt.sfm.SetCameraIntrinsicsFromPriors(recon) after setting all priors for each view?

**Comment by Heusini** [comment]
Ah okay this is done some lines below and works. 
https://github.com/urbste/pyTheiaSfM/blob/25a8cbf0f9cc8a4ba0b359948c0d294225aad18d/pytest/sfm_pipeline.py#L260
My problem is that i cannot get good results from the whole pipeline. Even with given key points the end result doesn't resemble anything

**Comment by urbste** [comment]
If you can share your data I can have a look.

Sebastian ***@***.***> schrieb am Di., 30. Mai 2023, 15:43:

**Comment by urbste** [comment]
Hi, I tested your dataset. With this I also updated the sfm_pipeline_fountain.py example and moved it to a different folder (pyexamples/). Also make sure to install the latest version 0.1.21 as I also updated one option in the bindings file.


``` bash
python pyexamples/sfm_pipeline_fountain.py --path_fountain_dataset /home/fountain_dataset --reconstruction incremental
```

For me this works without issues for either Global or Incremental reconstruction. Can you please check on your side?

![Bildschirmfoto vom 2023-06-01 08-05-15](https://github.com/urbste/pyTheiaSfM/assets/4609142/217ea5cc-aa1c-48a8-b4e6-58a0761658d6)

**Comment by Heusini** [comment]
Thanks that helped a lot
