### ISSUE TITLE
What exactly are the inputs of TwoPointPosePartialRotation ?

### ISSUE THREAD

**Issue by alexs7** [urbste/pyTheiaSfM#17]
From the code the inputs are:

```
int TwoPointPosePartialRotation(const Vector3d& axis,
                                const Vector3d& model_point_1,
                                const Vector3d& model_point_2,
                                const Vector3d& image_ray_1,
                                const Vector3d& image_ray_2,
                                Quaterniond soln_rotations[2],
                                Vector3d soln_translations[2]) 
```

The axis is the gravity axis as [0,-1,0] ?
The model points are the 3D points from the 2D-3D correspondences in world coordinates.
The image rays the bearing vectors of the 3D points after they have been transformed by the Rx and Rz of the IMU sensor?

**Comment by urbste** [comment]
Hi, I never used that function myself. Did you check the [tests](https://github.com/urbste/pyTheiaSfM/blob/master/src/theia/sfm/pose/two_point_pose_partial_rotation_test.cc)?  Or maybe the [paper](https://sites.cs.ucsb.edu/~holl/pubs/Sweeney-2015-ISMAR.pdf).

**Comment by alexs7** [comment]
Ok, I assume, from the tests, that the 2D bearing vectors (or image rays) and 3D points are already in the camera coordinate space. Then the tests back-project the 3D points in world points. 

So the input is 2D image rays in camera space and 3D points in world coordinate points, after being rotated by the Rx and Rz matrices from the IMU, to cancel those rotations according to http://theia-sfm.org/pose.html (last part).

Once the 2D bearing vectors and 3D world points have been rotated then the world and camera space should have the same case as in Figure 1 from the paper you linked. I hope this helps and I got it right
